# =============================================================================
# PART 2 — R: statistical modelling + ggplot
#
# HOW THIS WORKS
#   For each task: read the GOAL, copy the PROMPT into your AI assistant,
#   paste the returned code under "YOUR CODE", and run it (Ctrl/Cmd + Enter).
#   The CHECKPOINT states the expected output.
#
#   On error: copy the FULL error message back to the AI and say
#   "this is the error I got, fix it." That loop is most of the workflow.
#
#   Stuck? r/02_r_solution.R has working code for everything — a reference,
#   not a shortcut to skip the exercise.
#
# THE DATA is synthetic, generated by data/make_data.py. It is not real
#   patient data, which is why it can be pasted into a chatbot without
#   privacy concern. Never do this with real PHI. (Rationale and definitions:
#   guardrails/DATA_PRIVACY.md)
#
# THE TRAPS in Tasks 4 and 6 are documented, with the exact prompt to catch each,
#   in guardrails/STATISTICS_GUARDRAILS.md. Retain that file after the workshop.
# =============================================================================

# If this errors: Session > Set Working Directory > To Project Directory
stopifnot(dir.exists("data"))
dir.create("outputs", showWarnings = FALSE)


#### Task 1 — Load and join the data ---------------------------------------
#
# GOAL: read both CSVs, join them by participant_id, and inspect the result.
#
# PROMPT (copy everything between the lines into your AI):
# -----------------------------------------------------------------------------
# I'm a researcher using R in RStudio. I am a beginner. I use the tidyverse.
#
# I have two CSV files:
#   data/transcripts.csv - one row per participant. Columns: participant_id,
#     group ("control" or "aphasia"), age, sex, education_years,
#     months_post_onset, wab_aq (aphasia severity, 0-100, higher = less
#     impaired), transcript (what they said describing a picture).
#   data/features.csv - one row per participant. Columns: participant_id,
#     n_words, n_unique_words, type_token_ratio, mean_word_length,
#     content_word_ratio, filler_rate.
#
# Write R code (readr + dplyr) that reads both files, left-joins them by
# participant_id into a tibble called `df`, makes `group` a factor with
# "control" as the reference level, and then shows me the structure with
# glimpse(). Just the code with short comments, no explanation afterwards.
# -----------------------------------------------------------------------------

# YOUR CODE:



# CHECKPOINT: 60 rows, 14 columns. `group` should be a factor, not a character.


#### Task 2 — Descriptives by group ----------------------------------------
#
# GOAL: a table of means and SDs by group — a standard Table 1.
#
# PROMPT:
# -----------------------------------------------------------------------------
# Using `df`, make a summary table with one row per group showing: n, and the
# mean (SD) of age, wab_aq, n_words, and content_word_ratio. Format each cell as
# "mean (SD)" rounded sensibly. Use dplyr. Print it.
#
# Then run a Welch t-test comparing content_word_ratio between the two groups.
# -----------------------------------------------------------------------------

# YOUR CODE:



# CHECKPOINT: controls ~99.5 on the WAB and ~110 words; aphasia ~70.5 and ~70
# words. The t-test on content_word_ratio comes out around p = .016.
#
# ASK THE AI: "is a t-test the right test here, and what is it assuming?"
# The answer is generally sound — but note that it surfaces only on request.


#### Task 3 — A quick, ugly plot -------------------------------------------
#
# GOAL: scatterplot of wab_aq against content_word_ratio, coloured by group.
# Polish is not the point here; this plot is for looking, not publishing.
#
# PROMPT:
# -----------------------------------------------------------------------------
# Using ggplot2 and `df`, make a scatterplot with content_word_ratio on the x
# axis, wab_aq on the y axis, points coloured by group, and a straight linear
# fit line per group. Keep it minimal.
# -----------------------------------------------------------------------------

# YOUR CODE:



# CHECKPOINT: controls sit in a tight cloud near the top (all ~99 on the WAB).
# The aphasia group spreads out diagonally.
#
# This pattern motivates the next task.


#### Task 4 — The model ------------------------------------------------------
#
# GOAL: does lexical content predict aphasia severity?
#
# THE TRAP: modeling all 60 people at once yields a correlation that reflects
# nothing but the group difference — controls are pinned at ceiling on the WAB,
# so pooling just rediscovers that controls differ from patients. Restrict the
# model to the aphasia group. An AI assistant will not flag this.
#
# PROMPT:
# -----------------------------------------------------------------------------
# Using `df`, filter to the aphasia group only (call it `aph`). Fit a linear
# model predicting wab_aq from content_word_ratio, type_token_ratio, n_words and
# age. Show me the coefficients with 95% confidence intervals using broom::tidy,
# and the model fit statistics using broom::glance. Then produce the standard
# 2x2 diagnostic plots, and a correlation matrix of the three language
# predictors so I can check for multicollinearity.
# -----------------------------------------------------------------------------

# YOUR CODE:



# CHECKPOINT: R-squared = 0.66. Examine content_word_ratio specifically:
# alone it predicted wab_aq at p = .004; in this model, p = .055.
# No error, no warning — n_words absorbed its variance.
#
# ASK THE AI: "content_word_ratio predicts wab_aq at p = .004 on its own but only
# p = .055 in this model. Why?" Evaluate the answer independently.
#
# See guardrails/STATISTICS_GUARDRAILS.md #3 (ceiling/pooling) and #10 (the type-token
# ratio length confound) — both are active in this model.


#### Task 5 — Make it publication-ready ------------------------------------
#
# GOAL: turn the exploratory plot into a publication-ready figure.
# A strong use case for AI assistance — ggplot theme arguments are rarely
# worth memorizing.
#
# PROMPT:
# -----------------------------------------------------------------------------
# Take the scatterplot from before and make it publication-quality:
#   - points coloured AND shaped by group, slightly transparent
#   - a single linear fit line with a confidence band, fitted to the APHASIA
#     GROUP ONLY (not to the controls)
#   - x axis formatted as a percentage
#   - axis labels: "Content-word ratio" and "WAB Aphasia Quotient"
#   - a bold title, an informative subtitle giving the sample size, and a
#     caption saying the data are synthetic
#   - theme_minimal, base_size 12, legend at the bottom, no minor gridlines
#   - save it to outputs/figure1.png at 7x5 inches, 300 dpi
# -----------------------------------------------------------------------------

# YOUR CODE:



# CHECKPOINT: a figure suitable for showing a PI.
# Iterate: describe what to change and ask again — that is the workflow.


#### Task 6 (stretch) — Repeated measures ----------------------------------
#
# GOAL: model recovery over time in the longitudinal file — the same 30
# participants at ~1 month and ~12 months post-onset.
#
# THE TRAP: 60 rows but only 30 people. A plain lm() would treat every row as
# an independent person, producing an invalid p-value. A random intercept per
# participant is required.
#
# PROMPT:
# -----------------------------------------------------------------------------
# Read data/transcripts_long.csv into a data frame named `long`. It has 60 rows: 30 participants with aphasia,
# each measured at two timepoints ("acute" and "chronic"). Columns:
# participant_id, timepoint, months_post_onset, age, sex, education_years,
# wab_aq, transcript.
#
# These are repeated measures, so I need a mixed-effects model, not a plain lm.
# Using lme4, fit wab_aq predicted by timepoint with a random intercept for
# participant_id. Store the fitted model as `long_model`. Include all required
# library() calls. Make timepoint a factor with "acute" as the reference. Show me
# the summary and Wald confidence intervals.
#
# Then make a spaghetti plot: one grey line per participant across the two
# timepoints, with the group mean overlaid as a thicker coloured line.
# -----------------------------------------------------------------------------

# YOUR CODE:



# CHECKPOINT: chronic is +7.1 WAB points relative to acute, t = 5.2 — a clear
# improvement.
#
# Now fit the WRONG model deliberately and compare:
#     summary(lm(wab_aq ~ timepoint, data = long))
# It runs without error, returns p = .056, and reports the improvement as NOT
# significant. Treating 30 people as 60 discarded the pairing, and with it the
# power to detect a real effect.
#
# The wrong model did not invent an effect — it suppressed one. That direction
# of error is easy to miss.
#
# This is trap #1 (pseudoreplication) in guardrails/STATISTICS_GUARDRAILS.md — the single
# most consequential statistical error for repeated-measures rehab data.


#### Task 7 — The fact-check (do not skip this one) ------------------------
#
# GOAL: catch the AI misreporting your own results with unwarranted confidence.
#
# PROMPT:
# -----------------------------------------------------------------------------
# Write the Results paragraph for my linear model in APA style, reporting the
# coefficients, confidence intervals, R-squared, and F test.
# -----------------------------------------------------------------------------

# YOUR CODE:



# CHECK EVERY NUMBER against the actual output:
#   tidy(m1, conf.int = TRUE)
#   glance(m1)
#   nobs(m1)
#
# Common errors, roughly in order of frequency:
#   - degrees of freedom, invented or copied from elsewhere
#   - the DIRECTION of an effect (sign flipped, reported confidently)
#   - calling p = .07 "significant," or p = .12 "a trend towards significance"
#   - citing an R-squared or F statistic it never computed
#   - describing a non-significant predictor as significant
#
# A clean check on this run does not exempt future runs from the same check.
# The model is right most of the time, which is precisely what makes the
# errors easy to miss.
