# =============================================================================
# PART 2 — R: statistical modelling + ggplot
#
# HOW THIS WORKS
#   For each task: read the GOAL, copy the PROMPT into your AI assistant,
#   paste the code it gives you under "YOUR CODE", and run it (Ctrl/Cmd + Enter).
#   The CHECKPOINT tells you what a correct answer looks like.
#
#   When something errors: copy the WHOLE error message back to the AI and say
#   "this is the error I got, fix it." That loop is the job.
#
#   Stuck? r/02_r_solution.R has working code for everything. Use it as a
#   parachute, not as a shortcut.
#
# THE DATA is synthetic. It was generated by data/make_data.py. It is not real
#   patient data, which is why we can paste it into a chatbot with a clear
#   conscience. Never do this with real PHI. (Why, and what counts as PHI:
#   guardrails/DATA_PRIVACY.md)
#
# THE TRAPS in Tasks 4 and 6 are documented, with the exact prompt to catch each,
#   in guardrails/STATISTICS_GUARDRAILS.md. When you finish, keep that file.
# =============================================================================

# If this errors: Session > Set Working Directory > To Project Directory
stopifnot(dir.exists("data"))
dir.create("outputs", showWarnings = FALSE)


#### Task 1 — Load and join the data ---------------------------------------
#
# GOAL: read both CSVs, join them by participant_id, and look at the result.
#
# PROMPT (copy everything between the lines into your AI):
# -----------------------------------------------------------------------------
# I'm a researcher using R in RStudio. I am a beginner. I use the tidyverse.
#
# I have two CSV files:
#   data/transcripts.csv - one row per participant. Columns: participant_id,
#     group ("control" or "aphasia"), age, sex, education_years,
#     months_post_onset, wab_aq (aphasia severity, 0-100, higher = less
#     impaired), transcript (what they said describing a picture).
#   data/features.csv - one row per participant. Columns: participant_id,
#     n_words, n_unique_words, type_token_ratio, mean_word_length,
#     content_word_ratio, filler_rate.
#
# Write R code (readr + dplyr) that reads both files, left-joins them by
# participant_id into a tibble called `df`, makes `group` a factor with
# "control" as the reference level, and then shows me the structure with
# glimpse(). Just the code with short comments, no explanation afterwards.
# -----------------------------------------------------------------------------

# YOUR CODE:



# CHECKPOINT: 60 rows, 14 columns. `group` should be a factor, not a character.


#### Task 2 — Descriptives by group ----------------------------------------
#
# GOAL: a table of means and SDs by group — the Table 1 of any paper.
#
# PROMPT:
# -----------------------------------------------------------------------------
# Using `df`, make a summary table with one row per group showing: n, and the
# mean (SD) of age, wab_aq, n_words, and content_word_ratio. Format each cell as
# "mean (SD)" rounded sensibly. Use dplyr. Print it.
#
# Then run a Welch t-test comparing content_word_ratio between the two groups.
# -----------------------------------------------------------------------------

# YOUR CODE:



# CHECKPOINT: controls ~99.5 on the WAB and ~110 words; aphasia ~70.5 and ~70
# words. The t-test on content_word_ratio comes out around p = .016.
#
# NOW ASK THE AI: "is a t-test the right test here, and what is it assuming?"
# Read the answer. It's a good one — but notice that it only appeared because
# you asked. It would never have volunteered it.


#### Task 3 — A quick, ugly plot -------------------------------------------
#
# GOAL: scatterplot of wab_aq against content_word_ratio, coloured by group.
# Ugly is fine. Fast is the point. You are looking, not publishing.
#
# PROMPT:
# -----------------------------------------------------------------------------
# Using ggplot2 and `df`, make a scatterplot with content_word_ratio on the x
# axis, wab_aq on the y axis, points coloured by group, and a straight linear
# fit line per group. Keep it minimal.
# -----------------------------------------------------------------------------

# YOUR CODE:



# CHECKPOINT: the controls sit in a tight cloud at the top (they all score ~99
# on the WAB). The aphasia group spreads out diagonally.
#
# ^ That picture is the reason for the next task.


#### Task 4 — The model ------------------------------------------------------
#
# GOAL: does lexical content predict aphasia severity?
#
# THE TRAP: if you model all 60 people at once, you get a beautiful correlation
# that means nothing — controls are all pinned at ceiling on the WAB, so you'd
# really just be rediscovering that controls differ from patients. Model the
# aphasia group only. Your AI will not stop you. You have to know this.
#
# PROMPT:
# -----------------------------------------------------------------------------
# Using `df`, filter to the aphasia group only (call it `aph`). Fit a linear
# model predicting wab_aq from content_word_ratio, type_token_ratio, n_words and
# age. Show me the coefficients with 95% confidence intervals using broom::tidy,
# and the model fit statistics using broom::glance. Then produce the standard
# 2x2 diagnostic plots, and a correlation matrix of the three language
# predictors so I can check for multicollinearity.
# -----------------------------------------------------------------------------

# YOUR CODE:



# CHECKPOINT: R-squared = 0.66. Now look closely at content_word_ratio.
# On its own it predicted wab_aq at p = .004. In this model: p = .055.
# Your headline finding just became a footnote. Nothing errored. Nothing warned
# you. n_words quietly ate its variance.
#
# ASK THE AI: "content_word_ratio predicts wab_aq at p = .004 on its own but only
# p = .055 in this model. Why?" Then decide for yourself whether you believe it.
#
# See guardrails/STATISTICS_GUARDRAILS.md #3 (ceiling/pooling) and #10 (the type-token
# ratio length confound) — both are live in this exact model.


#### Task 5 — Make it publication-ready ------------------------------------
#
# GOAL: turn the ugly plot into a figure you'd actually put in a paper.
# This is the single best use of an AI coding assistant. Nobody memorises
# ggplot theme arguments. Nobody should.
#
# PROMPT:
# -----------------------------------------------------------------------------
# Take the scatterplot from before and make it publication-quality:
#   - points coloured AND shaped by group, slightly transparent
#   - a single linear fit line with a confidence band, fitted to the APHASIA
#     GROUP ONLY (not to the controls)
#   - x axis formatted as a percentage
#   - axis labels: "Content-word ratio" and "WAB Aphasia Quotient"
#   - a bold title, an informative subtitle giving the sample size, and a
#     caption saying the data are synthetic
#   - theme_minimal, base_size 12, legend at the bottom, no minor gridlines
#   - save it to outputs/figure1.png at 7x5 inches, 300 dpi
# -----------------------------------------------------------------------------

# YOUR CODE:



# CHECKPOINT: a figure you would not be embarrassed to show your PI.
# Now iterate: tell it what you don't like and ask again. That's the workflow.


#### Task 6 (stretch) — Repeated measures ----------------------------------
#
# GOAL: model recovery over time in the longitudinal file — the same 30
# participants at ~1 month and ~12 months post-onset.
#
# THE TRAP: 60 rows, but only 30 people. A plain lm() would treat every row as
# an independent person and give you a p-value that is a lie. You need a random
# intercept per participant.
#
# PROMPT:
# -----------------------------------------------------------------------------
# Read data/transcripts_long.csv. It has 60 rows: 30 participants with aphasia,
# each measured at two timepoints ("acute" and "chronic"). Columns:
# participant_id, timepoint, months_post_onset, age, sex, education_years,
# wab_aq, transcript.
#
# These are repeated measures, so I need a mixed-effects model, not a plain lm.
# Using lme4, fit wab_aq predicted by timepoint with a random intercept for
# participant_id. Make timepoint a factor with "acute" as the reference. Show me
# the summary and Wald confidence intervals.
#
# Then make a spaghetti plot: one grey line per participant across the two
# timepoints, with the group mean overlaid as a thicker coloured line.
# -----------------------------------------------------------------------------

# YOUR CODE:



# CHECKPOINT: chronic is +7.1 WAB points on acute, t = 5.2. Clear improvement.
#
# NOW DO THIS. Fit the WRONG model on purpose and compare:
#     summary(lm(wab_aq ~ timepoint, data = long))
# It runs perfectly. It gives you p = .056. It tells you the improvement is NOT
# significant — and it is wrong. Pretending 30 people are 60 people threw away the
# pairing, and with it, the power to see a real effect.
#
# The wrong model didn't invent an effect. It HID one. That's the direction nobody
# warns you about.
#
# This is trap #1 (pseudoreplication) in guardrails/STATISTICS_GUARDRAILS.md — the single
# most important statistical error for repeated-measures rehab data.


#### Task 7 — The fact-check (do not skip this one) ------------------------
#
# GOAL: catch the AI being confidently wrong about your own results.
#
# PROMPT:
# -----------------------------------------------------------------------------
# Write the Results paragraph for my linear model in APA style, reporting the
# coefficients, confidence intervals, R-squared, and F test.
# -----------------------------------------------------------------------------

# YOUR CODE:



# NOW CHECK EVERY SINGLE NUMBER against the real output:
#   tidy(m1, conf.int = TRUE)
#   glance(m1)
#   nobs(m1)
#
# Things it commonly gets wrong, in roughly this order:
#   - degrees of freedom, invented or copied from somewhere else
#   - the DIRECTION of an effect (it flips a sign and reports it confidently)
#   - calling p = .07 "significant", or p = .12 "a trend towards significance"
#   - citing an R-squared or an F statistic it never actually saw
#   - describing a predictor as significant when it isn't
#
# If it got everything right: good. Do it again tomorrow anyway. It is right
# most of the time, and that is exactly what makes the misses dangerous.
