# =============================================================================
# PART 2 - R: statistical modeling + ggplot
#
# HOW TO USE THIS FILE
#   Read the goal, copy the prompt into an AI assistant, paste the returned code
#   under "YOUR CODE", and run only that code with Ctrl/Cmd + Enter. The checkpoint
#   identifies the expected object or output.
#
#   On error, copy the full error and request the immediate cause and smallest correction.
#
#   `r/02_r_solution.R` is a reference implementation for recovery from an error.
#
# THE DATA are synthetic and generated by data/make_data.py. Do not treat that
#   status as permission to enter real participant data into an AI service.
#
# PROMPTS.md contains the workshop verification sequence. The guardrails folder
#   contains background material whose external claims require source audit before reuse.
# =============================================================================

# If this errors: Session > Set Working Directory > To Project Directory
stopifnot(dir.exists("data"))
dir.create("outputs", showWarnings = FALSE)


#### Task 1 - Load and join the data ---------------------------------------
#
# GOAL: read both CSVs, join them by participant_id, and inspect the result.
#
# PROMPT (copy everything between the lines into your AI):
# -----------------------------------------------------------------------------
# I'm a researcher using R in RStudio. I am a beginner. I use the tidyverse.
#
# I have two CSV files:
#   data/transcripts.csv - one row per participant. Columns: participant_id,
#     group ("control" or "aphasia"), age, sex, education_years,
#     months_post_onset, wab_aq (aphasia severity, 0-100, higher = less
#     impaired), transcript (what they said describing a picture).
#   data/features.csv - one row per participant. Columns: participant_id,
#     n_words, n_unique_words, type_token_ratio, mean_word_length,
#     content_word_ratio, filler_rate.
#
# Write R code (readr + dplyr) that reads both files, left-joins them by
# participant_id into a tibble called `df`, makes `group` a factor with
# "control" as the reference level, and then shows me the structure with
# glimpse(). Just the code with short comments, no explanation afterwards.
# -----------------------------------------------------------------------------

# YOUR CODE:



# CHECKPOINT: 60 rows, 14 columns. `group` should be a factor, not a character.


#### Task 2 - Descriptives by group ----------------------------------------
#
# GOAL: a table of means and SDs by group.
#
# PROMPT:
# -----------------------------------------------------------------------------
# Using `df`, make a summary table with one row per group showing: n, and the
# mean (SD) of age, wab_aq, n_words, and content_word_ratio. Format each cell as
# "mean (SD)" rounded sensibly. Use dplyr. Print it.
#
# Then run a Welch t-test comparing content_word_ratio between the two groups.
# -----------------------------------------------------------------------------

# YOUR CODE:



# CHECKPOINT: controls about 99.5 on the WAB and about 110 words; aphasia about 70.5 and about 70
# words. The t-test on content_word_ratio comes out around p = .016.
#
# ASK THE AI: "is a t-test the right test here, and what is it assuming?"
# Compare the response with the data structure and the stated question.


# Task 3 - Exploratory plot --------------------------------------------------
#
# GOAL: scatterplot of wab_aq against content_word_ratio, coloured by group.
# This plot is for inspecting the data before formal modeling.
#
# PROMPT:
# -----------------------------------------------------------------------------
# Using ggplot2 and `df`, make a scatterplot with content_word_ratio on the x
# axis, wab_aq on the y axis, points coloured by group, and a straight linear
# fit line per group. Keep it minimal.
# -----------------------------------------------------------------------------

# YOUR CODE:



# CHECKPOINT: controls sit in a tight cloud near the top (all ~99 on the WAB).
# The aphasia group spreads out diagonally.
#
# This pattern motivates the next task.


# Task 4 - The model ----------------------------------------------------------
#
# GOAL: does lexical content predict aphasia severity?
#
# The model is restricted to the aphasia group because the question concerns
# variation in WAB-AQ within that group. The control group clusters near the upper end
# of WAB-AQ in this synthetic dataset.
#
# PROMPT:
# -----------------------------------------------------------------------------
# Using `df`, filter to the aphasia group only (call it `aph`). Fit a linear
# model predicting wab_aq from content_word_ratio, type_token_ratio, n_words and
# age. Show me the coefficients with 95% confidence intervals using broom::tidy,
# and the model fit statistics using broom::glance. Then produce the standard
# 2x2 diagnostic plots, and a correlation matrix of the three language
# predictors so I can check for multicollinearity.
# -----------------------------------------------------------------------------

# YOUR CODE:



# CHECKPOINT: R-squared is 0.66. For content_word_ratio, the univariable model has
# p = .004; the adjusted model has p = .055. Compare the coefficient, uncertainty,
# and predictor correlation structure before interpreting this change.
#
# ASK THE AI: "content_word_ratio predicts wab_aq at p = .004 on its own but only
# p = .055 in this model. Why?" Evaluate the answer independently.
#
# The workshop data were constructed to show the distinction between a pooled group contrast,
# a within-group association, and a measure whose value changes with transcript length.


# Task 5 - Create a publication figure --------------------------------------
#
# GOAL: turn the exploratory plot into a figure suitable for a research presentation.
# The prompt specifies the analytic population, visual encodings, and output file.
#
# PROMPT:
# -----------------------------------------------------------------------------
# Take the scatterplot from before and prepare it for a research presentation:
#   - use filled points with a thin dark outline; use both shape and fill for group
#   - use teal for control and red for aphasia
#   - show one linear fit with a 95% confidence band for the APHASIA GROUP ONLY
#   - x axis formatted as a percentage
#   - axis labels: "Content-word ratio" and "WAB Aphasia Quotient"
#   - use a plain title, a subtitle giving the sample size, and a caption that
#     identifies the data as synthetic and the band as a 95% confidence interval
#   - use theme_minimal, base_size 11, a white background, a bottom legend without
#     a frame, and no minor gridlines
#   - save it to outputs/figure1.png at 7x5 inches, 300 dpi
# -----------------------------------------------------------------------------

# YOUR CODE:



# CHECKPOINT: a figure suitable for showing a PI.
# If a requirement is not met, describe the discrepancy and request a revision.


# Task 6 (stretch) - Repeated measures --------------------------------------
#
# GOAL: model change over time in the longitudinal file, which contains the same 30
# participants at about 1 month and 12 months post-onset.
#
# The 60 rows represent 30 participants measured twice. The random intercept represents
# within-participant dependence; the comparison below shows the consequence of omitting it.
#
# PROMPT:
# -----------------------------------------------------------------------------
# Read data/transcripts_long.csv into a data frame named `long`. It has 60 rows: 30 participants with aphasia,
# each measured at two timepoints ("acute" and "chronic"). Columns:
# participant_id, timepoint, months_post_onset, age, sex, education_years,
# wab_aq, transcript.
#
# These are repeated measures, so I need a mixed-effects model, not a plain lm.
# Using lme4, fit wab_aq predicted by timepoint with a random intercept for
# participant_id. Store the fitted model as `long_model`. Include all required
# library() calls. Make timepoint a factor with "acute" as the reference. Show me
# the summary and Wald confidence intervals.
#
# Then make a spaghetti plot: one grey line per participant across the two
# timepoints, with the group mean overlaid as a thicker coloured line.
# -----------------------------------------------------------------------------

# YOUR CODE:



# CHECKPOINT: chronic is 7.1 WAB points higher than acute in this synthetic dataset,
# with t = 5.2 in the mixed model.
#
# Now fit the WRONG model deliberately and compare:
#     summary(lm(wab_aq ~ timepoint, data = long))
# It runs without error and returns p = .056. Compare its standard error with the mixed-model
# standard error. The estimates use the same timepoint means, but the models represent different
# dependence structures.


#### Task 6B (advanced) - Treat time as continuous -------------------------
#
# GOAL: compare the categorical acute-versus-chronic model with a model that represents
# months since onset as a continuous predictor.
#
# PROMPT:
# -----------------------------------------------------------------------------
# Starting with the `long` data frame from the previous task, fit a second linear mixed-effects
# model named `month_model`. Predict wab_aq from months_post_onset and include a random intercept
# for participant_id. Show the model summary and Wald confidence intervals.
#
# Then explain, in four short bullets, the difference between `long_model`, which uses the
# categorical `timepoint` variable, and `month_model`, which uses continuous months_post_onset.
# State the estimand for each model, the time-course assumption made by each, and why the latter
# model does not establish that recovery is linear between the two observed visits.
# Give code first, then the four bullets.
# -----------------------------------------------------------------------------

# YOUR CODE:



# CHECKPOINT: the estimated change is about +0.64 WAB points per month, with a Wald 95% interval
# from 0.39 to 0.89. This is a compact description of the two-visit synthetic data, not evidence
# that recovery follows a linear monthly trajectory.


# Task 7 - Fact-check the result statement ----------------------------------
#
# GOAL: trace each result sentence to the displayed model output.
#
# PROMPT:
# -----------------------------------------------------------------------------
# Write the Results paragraph for my linear model in APA style, reporting the
# coefficients, confidence intervals, R-squared, and F test.
# -----------------------------------------------------------------------------

# YOUR CODE:



# CHECK EVERY NUMBER against the actual output:
#   tidy(m1, conf.int = TRUE)
#   glance(m1)
#   nobs(m1)
#
# Check the sign, interval, p value, degrees of freedom, R-squared, F statistic, and sample
# size against the displayed output. A correct statement here is not evidence that later
# statements can be accepted without the same output check.
